kind: pipeline
type: docker
name: pipeline-01

clone:
  disable: true

steps:
- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token: 
      from_secret: telegram_token
    to: 
      from_secret: telegram_to
    message: >
       {{#success build.status}}
         build {{build.number}} succeeded. Good job. ${DRONE_REPO_LINK}
       {{else}}
         build {{build.number}} send message ${DRONE_REPO_LINK}. Fix me please.
       {{/success}}