kind: pipeline
type: docker
name: default

steps:
  - name: ping mysql
    image: mysql
    commands:
    - sleep 10
    # - apt-get update
    # - echo "Y" | apt-get install iputils-ping
    # - ping mysqlhost -c 10
    - mysql -h mysqlhost -u root -p root

services:
  - name: mysqlhost
    image: mysql
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"