kind: pipeline
name: backend

steps:
- name: golang test
  image: golang:1.14-alpine
  environment:
    CGO_ENABLED: "0"
  commands:
    - go test -cover

volumes:
- name: docker
  host:
    path: /var/run/docker.sock