kind: pipeline
type: docker
name: pipeline-01

clone:
  disable: true

steps:
- name: practice
  image: golang
  commands:
    - echo hello drone pipeline-01

---

kind: pipeline
type: docker
name: pipeline-02

clone:
  disable: true

steps:
- name: practice
  image: golang
  commands:
    - echo hello drone pipeline-02

depends_on:
- pipeline-01

---

kind: pipeline
type: docker
name: pipeline-03


clone:
  disable: true

steps:
- name: practice
  image: golang
  commands:
    - echo hello drone pipeline-03

depends_on:
- pipeline-02
