kind: pipeline
type: docker
name: default

steps:
  - name: ping scylla
    image: scylladb/scylla:3.3.4
    commands:
    - sleep 50
    - cqlsh -e "SHOW VERSION" scylladb

services:
  - name: scylladb
    image: scylladb/scylla:3.3.4
    # command: ["--listen-address", "scylladb"]
  - name: scylladb2
    image: scylladb/scylla:3.3.4
    command: 
    - --seeds=scylladb
  - name: scylladb3
    image: scylladb/scylla:3.3.4
    command: 
    - --seeds=scylladb