kind: pipeline
type: docker
name: backend

steps:
- name: golang test
  image: golang
  commands:
  - docker build --no-cache --pull --force-rm -t rain/ithome:latest -f go.dockerfile .
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock