kind: pipeline
type: docker
name: default

steps:
  - name: ping mysql
    image: mysql:5.5
    commands:
    - sleep 10
    - mysql -hmysqlhost -uroot -proot

  - name: ping mysql
    image: mysql:5.5
    detach: true
    commands:
    - echo "hihihi detach is true"

services:
  - name: mysqlhost
    image: mysql:5.5
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: "root"