kind: pipeline
type: docker
name: default

steps:
  - name: ping redis
    image: redis
    commands:
    - sleep 5
    - redis-cli -h cachehost ping

  - name: ping mysql
    image: mysql
    commands:
    - sleep 5
    - apt-get update
    - echo "Y" | apt-get install iputils-ping
    - ping mysqlhost -c 10
    - mysql -h mysqlhost -u root -p root

services:
  - name: cachehost
    image: redis
  - name: mysqlhost
    image: mysql
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: "root"