kind: pipeline
type: docker
name: ithome_telegram_webhook

steps:
- name: ithome_alert
  image: appleboy/drone-telegram:1.3.8
  settings:
    token: 
      from_secret: telegram_token
    to: 
      from_secret: telegram_to
    message: "【溫馨提醒】動作開始!!"