kind: pipeline
type: docker
name: default

steps:
  - name: ping scylla
    image: scylladb/scylla:4.1.6
    commands:
    - sleep 10
    - apt-get update
    - echo "Y" | apt-get install iputils-ping
    - ping scylladb -c 10

services:
  - name: scylladb
    image: scylladb/scylla:4.1.6
