kind: pipeline
type: docker
name: backend

steps:
- name: make file to volumes path
  image: golang
  commands:
    - echo hello drone > hi.txt

  volumes:
  - name: tmp_dir
    path: /tmp

- name: check volumes file
  image: golang
  commands:
    - ls
  volumes:
  - name: tmp_dir
    path: /tmp

volumes:
- name: tmp_dir
  host:
    path: /tmp