kind: pipeline
type: docker
name: default

steps:
  - name: ping scylla
    image: scylladb/scylla:3.3.4
    commands:
    - sleep 50
    - cqlsh -e "SHOW VERSION" cassandra 

services:
  - name: cassandra
    image: scylladb/scylla:3.3.4
    command: ["--listen-address", "cassandra"]
  - name: cassandra-2
    image: scylladb/scylla:3.3.4
    command: 
    - --seeds=cassandra
  - name: cassandra-3
    image: scylladb/scylla:3.3.4
    command: 
    - --seeds=cassandra