kind: pipeline
type: docker
name: default

steps:
  - name: ping scylla
    image: cassandra:3.0
    commands:
    - sleep 50
    - cqlsh -e "SHOW VERSION" scylladb

services:
  - name: cassandra
    image: cassandra:3.0

  - name: cassandra2
    image: cassandra:3.0
    command: 
    - --seeds=cassandra

  - name: cassandra3
    image: cassandra:3.0
    command: 
    - --seeds=cassandra