kind: pipeline
type: docker
name: linter

steps:
- name: alert_production_ci
  detach: true
  image: appleboy/drone-telegram
  settings:
    token: 
      from_secret: telegram_token
    to: 
      from_secret: telegram_to
    message: "【溫馨提醒】〖ITHOME〗【鐵人賽】 發文動作開始!!"