kind: pipeline
type: docker
name: default

steps:
  - name: ping redis
    image: redis
    commands:
    - sleep 5
    - redis-cli -h cachehost ping

  - name: ping mysql
    image: mysql
    commands:
    - sleep 5
    - ping mysqlhost

services:
  - name: cachehost
    image: redis
  - name: mysqlhost
    image: mysql
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: "root"