kind: pipeline
type: docker
name: default

steps:
  - name: ping scylla
    image: scylladb/scylla:4.1.6
    commands:
    - sleep 10
    - scylladb cqlsh 

services:
  - name: scylladb
    image: scylladb/scylla:4.1.6
