kind: pipeline
type: docker
name: default

steps:
  - name: ping
    image: redis
    detach: true
    commands:
    - sleep 5
    - redis-cli -h cachehost ping

services:
  - name: cachehost
    image: redis