kind: pipeline
type: docker
name: pipeline-01

steps:
- name: practice
  image: golang
  commands:
    - echo hello drone pipeline-01

---

kind: pipeline
type: docker
name: pipeline-02

steps:
- name: practice
  image: golang
  commands:
    - echo hello drone pipeline-02

---

kind: pipeline
type: docker
name: pipeline-03

steps:
- name: practice
  image: golang
  commands:
    - echo hello drone pipeline-03