kind: pipeline
type: docker
name: backend

steps:
- name: practice make file
  image: golang
  commands:
    - ls /tmp
    - echo hello drone > /tmp/hi.txt

  volumes:
  - name: mylog
    path: /tmp

- name: check volumes file
  image: golang
  commands:
    - ls /tmp
  volumes:
  - name: mylog
    path: /tmp

volumes:
- name: mylog
  host:
    path: /tmp