kind: pipeline
type: docker
name: pipeline-01

steps:
- name: send telegram notification
  image: golang
  commands:
  - echo ${DRONE_COMMIT_SHA}
  - echo ${DRONE_COMMIT_SHA:10}
  - echo ${DRONE_COMMIT_SHA:8}