kind: pipeline
type: docker
name: default

steps:
  - name: golangci-lint
    image: golangci/golangci-lint:v1.31.0-alpine
    commands:
      - golangci-lint run

  - name: gcp_push_image
    image: docker:dind
    commands:
    - docker build --no-cache --pull --force-rm -t ithome/${DRONE_REPO_NAME}:latest -f go.dockerfile .

volumes:
- name: docker
  host:
    path: /var/run/docker.sock