kind: pipeline
type: docker
name: pipeline-01

clone:
  disable: true

steps:
- name: steps 01
  image: golang
  commands:
    - echo hello drone steps 01
    - ls abcdefg

- name: steps 02
  image: golang
  commands:
    - echo hello drone steps 02

- name: steps 03
  image: golang
  commands:
    - echo hello drone steps 03