kind: pipeline
type: docker
name: default

steps:
  - name: ping scylla
    image: mysql:5.5
    commands:
    - sleep 10
    - apk update && apk --no-cache add iputils-ping
    - ping scylladb -c 10

services:
  - name: scylladb
    image: scylladb/scylla:4.1.6
