kind: pipeline
type: docker
name: default

steps:
  - name: ping scylla
    image: scylladb/scylla:3.2.1
    commands:
    - sleep 50
    - cqlsh scylladb

services:
  - name: scylladb
    image: scylladb/scylla:3.2.1
    command: ["--experimental", "1", "--smp", "1", "--cpuset", "1", "--listen-address", "cassandra"]