kind: pipeline
type: docker
name: backend

steps:
- name: practice make file
  image: golang
  commands:
    - echo hello drone > /tmp/hi.txt

  volumes:
  - name: tmp_dir
    path: /tmp

- name: check volumes file
  image: golang
  commands:
    - ls /tmp
  volumes:
  - name: tmp_dir
    path: /tmp

volumes:
- name: tmp_dir
  host:
    path: /tmp